devices:
  - name: MKT001
    address: 10.10.1.1
    user: prometheus
    password: $ecretP@ssword
  - name: MKT002
    address: 10.10.2.1
    user: prometheus
    password: $ecretP@ssword
  - name: MKT003
    address: 10.10.3.1
    user: prometheus
    password: $ecretP@ssword
  - name: MKT004
    address: 10.10.3.1
    user: prometheus
    password: $ecretP@ssword
  # - name: routers_srv_dns
  #   srv:
  #     record: _mikrotik._udp.example.com
  #   user: prometheus
  #   password: password_to_all_dns_routers
  # - name: routers_srv_custom_dns
  #   srv:
  #     record: _mikrotik2._udp.example.com
  #     dns:
  #       address: 1.1.1.1
  #       port: 53
  #   user: prometheus
  #   password: password_to_all_dns_routers

features:
  bgp: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  # bgp: true
  # conntrack: true
  # dhcp: true
  # dhcpv6: true
  # dhcpl: true
  # routes: true
  # pools: true
  # optics: true
  # wlansta: true
  # wlanif: true
  # ipsec: true
  # lte: true
  # netwatch: true