---
# docker-compose -p mikrotik-exporter -f mikrotik-exporter.yaml up -d
version: "3"
services:
  mikrotik-exporter:
    image: nshttpd/mikrotik-exporter:1.0.11
    container_name: mikrotik-exporter
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - config:/config
    ports:
      - 9436:9436/tcp
volumes:
  config: